### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JohnRabin2357** [vertesan/gakumasu-diff#1]
Can you tell me how you generate the yaml files?

**Comment by vertesan** [comment]
I'm not sure if you are asking "how to convert the database from its original format to yaml" or "how to retrieve the database from the game". If the former, there are a whole bunch of production ready libraries can help you with it, doing a quick search perhaps it the most efficient way. If the latter, you will need to intercept the encrypted traffic and find a way to decrypt it.
