### ISSUE TITLE
The database needs to be updated.

### ISSUE THREAD

**Issue by Dreaminko** [vertesan/gakumasu-diff#2]
New content has been updated in-game.

**Comment by vertesan** [comment]
It is supposed to be automatically updated by a backend cronjob every one hour without the need of human actions.

Please be patient.

**Comment by Dreaminko** [comment]
The README should be edited now. 😂
![image](https://github.com/user-attachments/assets/f1890ca9-8195-456a-9f2c-d5d5a4a8f572)

**Comment by vertesan** [comment]
Ah... you got the point.
I will get it changed later.
